version: '3.8'

services:
  db:
    image: postgres:15
    container_name: archery_app_db
    restart: on-failure
    environment:
      POSTGRES_USER: archery_user
      POSTGRES_PASSWORD: archery_password
      POSTGRES_DB: archery_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
