packages:
  - '.'

ignoredBuiltDependencies:
  - '@nestjs/core'
  - bcrypt

overrides:
  '@isaacs/brace-expansion': '>=5.0.1'
  glob: '>=10.5.0'
  lodash: '>=4.17.23'
  tmp: '>=0.2.4'
  webpack: '>=5.104.1'
